site_url: https://gallant-archimedes-61f424.netlify.app//
logo_url: https://gallant-archimedes-61f424.netlify.app//icon.png

publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: master
  squash_merges: true

media_folder: static/img
public_folder: /img

# Docs: https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - label: 'Site settings'
    name: 'site'
    files:
      - label: 'Info'
        name: 'info'
        file: 'content/site/info.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - { label: Site Name, name: sitename, widget: string, hint: 'This is used for the site title' }
          - {
              label: Site Description,
              name: sitedescription,
              widget: string,
              hint: 'This is used as descriptive text for links that link to this site',
            }
          - {
              label: Site Language,
              name: sitelang,
              widget: string,
              pattern: ['^[a-z]{2}([-])?([A-Za-z]{2})?$', 'Must match "xx" or "xx-XX" syntax (ex. "en" or "sv-SE")'],
            }
          # - { label: Site Email, name: siteemail, widget: string, required: false }
  - name: 'blog'
    label: 'Posts'
    folder: 'content/blog'
    create: true
    format: 'frontmatter'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    # editor:
    #   preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - {
          label: 'Post Type',
          name: 'tags',
          widget: 'select',
          default: 'select an tag',
          multiple: true,
          options:
            [
              { label: 'Increazy E-commerce', value: 'increazy ecommerce' },
              { label: 'Increazy CLI', value: 'increazy cli' },
              { label: 'Increazy Checkout', value: 'increazy checkout' },
              { label: 'Increazy Pay', value: 'increazy pay' },
              { label: 'Business', value: 'business' },
              { label: 'Tech', value: 'tech' },
            ],
        }
      - { label: 'Body', name: 'body', widget: 'markdown', required: false }
  - name: 'docs'
    label: 'Documentation'
    folder: 'content/docs'
    create: true
    format: 'frontmatter'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    # editor:
    #   preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown', required: false }
      - {
          label: 'Doc Type',
          name: 'tags',
          widget: 'select',
          default: 'select an tag',
          multiple: true,
          options:
            [
              { label: 'Hooks', value: 'hooks' },
              { label: 'Pages', value: 'pages' },
              { label: 'Components', value: 'components' },
              { label: 'Loading', value: 'skeleton' },
              { label: 'Vtex', value: 'vtex' },
              { label: 'Magento 1.9.x', value: 'magento 1.9.x' },
              { label: 'Magento 2.3.x', value: 'magento 2.3.x' },
              { label: 'Assets', value: 'assets' },
              { label: 'Publication', value: 'publication' },
              { label: 'Deploy', value: 'deploy' },
            ],
        }
